"""
Provenance Guard — Flask app (Milestone 5: production layer)

Implemented:
  POST /submit          — full pipeline: both signals + confidence engine + real labels
  GET  /log              — structured audit log entries, joined with appeals
  POST /appeal           — appeal workflow: validate, log, flip status to under_review
  GET  /status/<id>      — lookup current verdict/status/appeal for a submission

Rate limiting: 10/minute, 100/day on POST /submit (Flask-Limiter, in-memory storage).
"""

import hashlib
import os
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from audit import (
    get_appeal,
    get_log,
    get_submission,
    init_db,
    insert_appeal,
    insert_submission,
    update_status,
)
from signals import classify_with_llm
from stylometrics import analyze_stylometrics

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)


# ---------------------------------------------------------------------------
# Confidence Scoring Engine (M4 — full implementation)
# ---------------------------------------------------------------------------

def compute_confidence(llm_score, stylometric_score) -> dict:
    """
    Combines Signal 1 (LLM) and Signal 2 (stylometric) per spec:
      - Both present: weighted 0.65/0.35, with disagreement penalty if |diff| > 0.35
      - Only LLM: capped at 0.65
      - Only stylometric: capped at 0.60
      - Neither: 0.5, forced uncertain
    """
    if llm_score is None and stylometric_score is None:
        return {"combined_score": 0.5, "verdict": "uncertain", "disagreement_flagged": False}

    if llm_score is not None and stylometric_score is None:
        score = min(llm_score, 0.65)
        return {"combined_score": round(score, 4), "verdict": _score_to_verdict(score), "disagreement_flagged": False}

    if llm_score is None and stylometric_score is not None:
        score = min(stylometric_score, 0.60)
        return {"combined_score": round(score, 4), "verdict": _score_to_verdict(score), "disagreement_flagged": False}

    # --- Both signals present: full weighted formula ---
    combined = llm_score * 0.65 + stylometric_score * 0.35
    disagreement = abs(llm_score - stylometric_score) > 0.35
    if disagreement:
        combined = combined * 0.85 + 0.5 * 0.15

    combined = max(0.0, min(combined, 1.0))
    return {
        "combined_score": round(combined, 4),
        "verdict": _score_to_verdict(combined),
        "disagreement_flagged": disagreement,
    }




def _score_to_verdict(score: float) -> str:
    """
    Spec threshold table (5 bands):
      0.00-0.28  human   (high-confidence human)
      0.29-0.42  human   (lean-human, still cautious label)
      0.43-0.72  uncertain
      0.73-0.87  ai      (lean-AI, still cautious label)
      0.88-1.00  ai      (high-confidence ai)
    """
    if score <= 0.42:
        return "human"
    if score <= 0.87:
        return "uncertain" if score <= 0.72 else "ai"
    return "ai"


def generate_label(combined_score: float, verdict: str) -> str:
    """
    Maps combined_score to one of five verbatim label variants per spec.
    Text must match exactly — these are shown directly to readers.
    """
    if combined_score <= 0.28:
        return (
            "✓ This content appears to be human-authored.\n\n"
            "Our analysis found no strong indicators of AI generation. "
            "This label reflects our best assessment — not a guarantee."
        )
    if combined_score <= 0.42:
        return (
            "~ Authorship unclear — likely human.\n\n"
            "Our analysis found more human-like patterns than AI-like ones, but the "
            "evidence isn't strong enough for a confident assessment. Some human writing "
            "styles can resemble AI output. If you're the creator and believe this label "
            "is wrong, you can submit an appeal."
        )
    if combined_score <= 0.72:
        return (
            "~ Authorship unclear.\n\n"
            "Our analysis couldn't confidently determine whether this content was written "
            "by a human or generated by AI. This does not mean the content is AI-generated "
            "— it means our system is uncertain. If you're the creator and believe this "
            "label is inaccurate, you can submit an appeal."
        )
    if combined_score <= 0.87:
        return (
            "~ Authorship unclear — some AI-like patterns detected.\n\n"
            "Our analysis found patterns that appear more often in AI-generated content "
            "than in human writing, but we're not confident enough to make a definitive "
            "call. Some human writing — especially formal, polished, or conventionally "
            "structured work — can resemble AI output. If this is your original work, you "
            "can submit an appeal."
        )
    return (
        "⚠ This content shows strong indicators of AI generation.\n\n"
        "Our analysis found consistent patterns across multiple signals that are "
        "characteristic of AI-generated text. This label reflects our best assessment — "
        "it is not a guaranteed determination. If you believe this is incorrect, you can "
        "submit an appeal."
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.post("/submit")
@limiter.limit("10 per minute;100 per day")
def submit():
    body = request.get_json(silent=True)
    if not body or not body.get("content"):
        return jsonify({"error": "Request body must include a non-empty 'content' field."}), 400

    raw_text = body["content"].strip()
    if not raw_text:
        return jsonify({"error": "'content' must not be blank."}), 400

    creator_id = body.get("creator_id", "")
    submission_id = str(uuid.uuid4())
    text_hash = hashlib.sha256(raw_text.encode()).hexdigest()

    # --- Signal 1: LLM classifier ---
    llm_result = classify_with_llm(raw_text)
    llm_score = llm_result["llm_score"]
    llm_reasoning = llm_result["reasoning"]

    # --- Signal 2: Stylometric analyzer ---
    stylo_result = analyze_stylometrics(raw_text)
    stylometric_score = stylo_result["stylometric_score"]
    short_text_warning = stylo_result["short_text_warning"]

    # --- Confidence engine ---
    confidence_result = compute_confidence(llm_score, stylometric_score)
    combined_score = confidence_result["combined_score"]
    verdict = confidence_result["verdict"]

    # --- Label ---
    label = generate_label(combined_score, verdict)

    # --- Audit log ---
    ts = insert_submission(
        submission_id=submission_id,
        creator_id=creator_id,
        text_hash=text_hash,
        verdict=verdict,
        confidence=combined_score,
        llm_score=llm_score,
        stylometric_score=stylometric_score,
        llm_reasoning=llm_reasoning,
        label=label,
        short_text_warning=short_text_warning,
    )

    return jsonify({
        "submission_id": submission_id,
        "verdict": verdict,
        "confidence": combined_score,
        "label": label,
        "signals": {
            "llm_score": llm_score,
            "llm_reasoning": llm_reasoning,
            "stylometric_score": stylometric_score,
            "stylometric_detail": stylo_result["detail"],
        },
        "short_text_warning": short_text_warning,
        "status": "classified",
        "timestamp": ts,
    })


@app.get("/log")
def log():
    limit = int(request.args.get("limit", 50))
    offset = int(request.args.get("offset", 0))
    verdict_filter = request.args.get("verdict")
    entries = get_log(limit=limit, offset=offset, verdict_filter=verdict_filter)
    return jsonify({"count": len(entries), "entries": entries})


@app.post("/appeal")
def appeal():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    submission_id = body.get("submission_id") or body.get("content_id")
    creator_id = body.get("creator_id")
    reasoning = body.get("reasoning") or body.get("creator_reasoning")

    if not submission_id or not creator_id or not reasoning:
        return jsonify({
            "error": "Request must include 'submission_id' (or 'content_id'), "
                     "'creator_id', and 'reasoning' (or 'creator_reasoning')."
        }), 400

    if not (10 <= len(reasoning) <= 2000):
        return jsonify({"error": "'reasoning' must be between 10 and 2000 characters."}), 400

    # 1. Validate submission exists
    record = get_submission(submission_id)
    if record is None:
        return jsonify({"error": f"No submission found with id '{submission_id}'."}), 404

    # 2. Validate no prior appeal exists
    existing = get_appeal(submission_id)
    if existing is not None:
        return jsonify({
            "error": "An appeal already exists for this submission.",
            "existing_appeal": {
                "appeal_id": existing["appeal_id"],
                "submission_id": existing["submission_id"],
                "creator_id": existing["creator_id"],
                "reasoning": existing["reasoning"],
                "timestamp": existing["timestamp"],
            },
        }), 409

    # 3. Write appeal entry
    appeal_id = str(uuid.uuid4())
    ts = insert_appeal(
        appeal_id=appeal_id,
        submission_id=submission_id,
        creator_id=creator_id,
        reasoning=reasoning,
        original_verdict=record["verdict"],
        original_confidence=record["confidence"],
    )

    # 4. Update status: classified -> under_review
    update_status(submission_id, "under_review")

    # 5. Return confirmation
    return jsonify({
        "appeal_id": appeal_id,
        "submission_id": submission_id,
        "status": "under_review",
        "message": "Your appeal has been received and logged. A human moderator will review "
                    "the original decision alongside your explanation.",
        "timestamp": ts,
    })


@app.get("/status/<submission_id>")
def status(submission_id):
    record = get_submission(submission_id)
    if record is None:
        return jsonify({"error": f"No submission found with id '{submission_id}'."}), 404

    appeal_record = get_appeal(submission_id)
    appeal_payload = None
    if appeal_record:
        appeal_payload = {
            "appeal_id": appeal_record["appeal_id"],
            "creator_id": appeal_record["creator_id"],
            "reasoning": appeal_record["reasoning"],
            "timestamp": appeal_record["timestamp"],
        }

    return jsonify({
        "submission_id": record["submission_id"],
        "verdict": record["verdict"],
        "confidence": record["confidence"],
        "label": record["label"],
        "status": record["status"],
        "appeal": appeal_payload,
    })


# ---------------------------------------------------------------------------
# Startup — init DB on every load (safe to call multiple times)
# ---------------------------------------------------------------------------

with app.app_context():
    init_db()

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"[provenance-guard] Starting on http://localhost:{port}")
    app.run(debug=True, port=port)