"""
Signal 1: LLM-based holistic classifier via Groq.

Spec contract:
  - Input: raw text string
  - Output: {"llm_score": float 0.0–1.0, "reasoning": str}
    OR {"llm_score": None, "reasoning": None} on failure
  - 0.0 = almost certainly human, 1.0 = almost certainly AI
"""

import json
import os
from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are an authorship analyst. Assess whether the following text was written by a human "
    "or generated by an AI. Return only a JSON object with fields `ai_probability` (float 0.0–1.0) "
    "and `reasoning` (one sentence). Do not include any other text."
)


def classify_with_llm(text: str) -> dict:
    """
    Send text to Groq LLM and return ai_probability score + reasoning.
    Returns {"llm_score": None, "reasoning": None} on any failure.
    """
    try:
        client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown fences if the model wraps in ```json ... ```
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
        score = max(0.0, min(1.0, score))  # clamp to [0, 1]

        return {"llm_score": score, "reasoning": parsed.get("reasoning", "")}

    except Exception as exc:
        print(f"[LLM classifier] failure: {exc}")
        return {"llm_score": None, "reasoning": None}


# ---------------------------------------------------------------------------
# Quick smoke-test — run this file directly: python signals.py
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    samples = [
        (
            "human-novel",
            "She had not gone to sleep at all. She lay in the dark and listened to the "
            "rain tick against the window, thinking about nothing in particular and "
            "everything at once, the way you do at three in the morning when the day "
            "has been too long and the night isn't long enough.",
        ),
        (
            "ai-style",
            "Artificial intelligence is transforming numerous industries by enabling "
            "organizations to automate repetitive tasks, enhance decision-making processes, "
            "and unlock valuable insights from vast datasets. As machine learning algorithms "
            "continue to advance, businesses are increasingly leveraging these technologies "
            "to achieve competitive advantages and drive innovation.",
        ),
        (
            "borderline-blog",
            "I've been thinking a lot about productivity lately. There are several strategies "
            "that have helped me stay focused throughout the day. First, I try to tackle "
            "the most important task early in the morning. Second, I limit distractions "
            "by turning off notifications. Finally, I take regular breaks to recharge.",
        ),
    ]

    for label, text in samples:
        result = classify_with_llm(text)
        print(f"\n[{label}]")
        print(f"  llm_score : {result['llm_score']}")
        print(f"  reasoning : {result['reasoning']}")